name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - uses: awvwgk/setup-fortran@main
        id: setup-fortran
        with:
          compiler: gcc
          version: 11

      - name: ssh_session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true

      - name: Build wheels (Not Windows)
        if: runner.os != 'Windows'
        uses: pypa/cibuildwheel@v2.16.2

      - name: Build wheels (Windows)
        if: runner.os == 'Windows'
        uses: pypa/cibuildwheel@v2.16.2
        env:
          CMAKE_GENERATOR: MinGW Makefiles

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  make_sdist:
    name: Make SDist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build SDist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz
