name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: ${{ matrix.os }}_${{ matrix.python_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python_version: ['3.8', '3.11']

    steps:
      - uses: actions/checkout@v3

      - uses: awvwgk/setup-fortran@main
        id: setup-fortran
        with:
          compiler: gcc
          version: 11

      - uses: dtolnay/rust-toolchain@stable

      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}

      - name: windows_specific_set_up
        if: runner.os == 'Windows'
        run: >
          export CMAKE_GENERATOR="MinGW Makefiles"

      - name: which_python
        run: which python

      - name: which_pip
        run: which pip

      - name: which_python3
        run: which python3

      - name: which_shell
        run: ps -p $$

      - name: build
        shell: bash -el {0}
        run: python3 -m pip install -v $GITHUB_WORKSPACE

      - name: test
        shell: bash -el {0}
        run: python3 -m pytest -m "not slow" $GITHUB_WORKSPACE

  make_sdist:
    name: make_sdist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: build_sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz
